sfdc:
  username: "![d8GRB3DgydOnztClv3XU2+mXDNrYA61/QKFmQtauEE0MRRZ90b1U+5uRMUwz2wDu]"
  password: "![eVJvrFy3f+jF9WrXJvxEJgvFIO09N3lR5dSEKtOEr2o=]"
  token: "![neYwQsHahfxt2BVbuJtB8qU7R/33T7B9mJOnsZop7PM=]" 
tls:
  keypass: "![t50QDKeKXbzCmlKY9a81zg==]"
  pass: "![t50QDKeKXbzCmlKY9a81zg==]"