#%RAML 1.0 NamedExample
{
    "Items": {
        "1": {
            "Product_Title": "REALME-NARZO-N55-6GB-64GB",
            "Warranty": "1-Years",
            "Quantity": 1,
            "Price": 18500,
            "Delivery_Charge": 100,
            "Total_Price": 18600,
            "Shipping_Warehouse_Location": "Kolkata",
            "Add_to_cart_Date": "2023-07-15",
            "Expected_Delivery": "2-Days",
            "Nearest_Db_Location": "Kolkata"
        },
        "2": {
            "Product_Title": "REDMI-PRO-11-6GB-128GB",
            "Warranty": "2-Years",
            "Quantity": 4,
            "Price": 18000,
            "Delivery_Charge": 100,
            "Total_Price": 72100,
            "Shipping_Warehouse_Location": "Kolkata",
            "Add_to_cart_Date": "2023-07-15",
            "Expected_Delivery": "2-Days",
            "Nearest_Db_Location": "Kolkata"
        },
        "3": {
            "Product_Title": "SAMSUNG-GALAXY-6GB-128GB",
            "Warranty": "3-Years",
            "Quantity": 1,
            "Price": 22000,
            "Delivery_Charge": 100,
            "Total_Price": 22100,
            "Shipping_Warehouse_Location": "Kolkata",
            "Add_to_cart_Date": "2023-07-17",
            "Expected_Delivery": "2-Days",
            "Nearest_Db_Location": "Kolkata"
        }
    },
    "Total_Amount": 112800
}