#%RAML 1.0 NamedExample
{
				"orderId" : "a035i00000Bwioj",
				"productTitle": "SAMSUNG-A2-4GB-64GB",
				"quantity": 1,
				"customerId": "KOL_1234",
				"complaint_category":"Wrong_Items",
				"description": "Bad product"
}