#%RAML 1.0 NamedExample

{
  "customerId": "KOL_1004",
  "emailId": "pratik@gmail.com",
  "firstName": "Pratik",
  "lastName": "Biswas",
  "gender": "Male",
  "pincode": "700004",
  "address": "Lalit Mitra Lane",
  "phoneNumber": "7980839906",
  "location": "Kolkata",
  "cardDetails" :
  {
    "1":{		  
    	"bankName" : "PNB",
    	"cardNumber" : "1111222233334444"
    }
  }
}
  