#%RAML 1.0 NamedExample
{
  "address": "lalit mitra lane",
  "pincode": "700004",
  "phoneNumber": "7980839906",
  "cardDetails": {
    "1": {
      "bankName": "PNB",
      "cardNumber": "1111222233334444"
    },
    "2": {
      "bankName": "ICICI",
      "cardNumber": "5555666677778888"
    }
  }
}