#%RAML 1.0 NamedExample
{
    "apiName": "App",
    "apiVersion": "Version",
    "server": "server",
    "env": "",
    "status": "UP",
    "message": "Alive",
    "details": {
        "stat": "Alive"
    }
}