[
  {
    "orderId__c": "a035i00000Bwioj",
    "productTitle__c": "SAMSUNG-A2-4GB-64GB",
    "quantity__c": "1.0",
    "customerId__c": "KOL_1234",
    "date_of_complaint__c": "2023-07-18",
    "status__c": "Active",
    "Id": null,
    "type": "complaint__c",
    "description__c": "Bad product",
    "action__c": null,
    "complaint_category__c": "Wrong_Items",
    "Name": "a065i00000JjaaV"
  },
  {
    "orderId__c": "a035i00000Bwioj",
    "productTitle__c": "SAMSUNG-A2-4GB-64GB",
    "quantity__c": "1.0",
    "customerId__c": "KOL_1234",
    "date_of_complaint__c": "2023-07-18",
    "status__c": "Closed",
    "Id": null,
    "type": "complaint__c",
    "description__c": "Bad product",
    "action__c": "None",
    "complaint_category__c": "Wrong_Items",
    "Name": "a065i00000JjafQ"
  },
  {
    "orderId__c": "a035i00000Bwioj",
    "productTitle__c": "SAMSUNG-A2-4GB-64GB",
    "quantity__c": "1.0",
    "customerId__c": "KOL_1234",
    "date_of_complaint__c": "2023-07-18",
    "status__c": "Closed",
    "Id": null,
    "type": "complaint__c",
    "description__c": "Bad product",
    "action__c": "None",
    "complaint_category__c": "Wrong_Items",
    "Name": "a065i00000JjafL"
  },
  {
    "orderId__c": "a035i00000Bwioj",
    "productTitle__c": "SAMSUNG-A2-4GB-64GB",
    "quantity__c": "1.0",
    "customerId__c": "KOL_1234",
    "date_of_complaint__c": "2023-07-18",
    "status__c": "Active",
    "Id": null,
    "type": "complaint__c",
    "description__c": "Bad product",
    "action__c": null,
    "complaint_category__c": "Wrong_Items",
    "Name": "a065i00000Jjaer"
  },
  {
    "orderId__c": "a035i00000Bwioj",
    "productTitle__c": "SAMSUNG-A2-4GB-64GB",
    "quantity__c": "1.0",
    "customerId__c": "KOL_1234",
    "date_of_complaint__c": "2023-07-18",
    "status__c": "Active",
    "Id": null,
    "type": "complaint__c",
    "description__c": "Bad product",
    "action__c": null,
    "complaint_category__c": "Wrong_Items",
    "Name": "a065i00000JjafG"
  },
  {
    "orderId__c": "a035i00000Bwioj",
    "productTitle__c": "SAMSUNG-A2-4GB-64GB",
    "quantity__c": "1.0",
    "customerId__c": "KOL_1234",
    "date_of_complaint__c": "2023-07-20",
    "status__c": "Closed",
    "Id": null,
    "type": "complaint__c",
    "description__c": "Bad product",
    "action__c": "None",
    "complaint_category__c": "Wrong_Items",
    "Name": "a065i00000JjawV"
  },
  {
    "orderId__c": "a035i00000Bwioj",
    "productTitle__c": "SAMSUNG-A2-4GB-64GB",
    "quantity__c": "1.0",
    "customerId__c": "KOL_1234",
    "date_of_complaint__c": "2023-07-28",
    "status__c": "Active",
    "Id": null,
    "type": "complaint__c",
    "description__c": "Bad product",
    "action__c": null,
    "complaint_category__c": "Wrong_Items",
    "Name": "a065i00000JkVwC"
  },
  {
    "orderId__c": "a035i00000Bwioj",
    "productTitle__c": "SAMSUNG-A2-4GB-64GB",
    "quantity__c": "1.0",
    "customerId__c": "KOL_1234",
    "date_of_complaint__c": "2023-07-28",
    "status__c": "Active",
    "Id": null,
    "type": "complaint__c",
    "description__c": "Bad product",
    "action__c": null,
    "complaint_category__c": "Wrong_Items",
    "Name": "a065i00000JkVw7"
  },
  {
    "orderId__c": "a035i00000Bwioj",
    "productTitle__c": "SAMSUNG-A2-4GB-64GB",
    "quantity__c": "1.0",
    "customerId__c": "KOL_1234",
    "date_of_complaint__c": "2023-07-28",
    "status__c": "Active",
    "Id": null,
    "type": "complaint__c",
    "description__c": "Bad product",
    "action__c": null,
    "complaint_category__c": "Wrong_Items",
    "Name": "a065i00000JkVvY"
  },
  {
    "orderId__c": "a035i00000Bwioj",
    "productTitle__c": "SAMSUNG-A2-4GB-64GB",
    "quantity__c": "3.0",
    "customerId__c": "KOL_1234",
    "date_of_complaint__c": "2023-07-28",
    "status__c": "Active",
    "Id": null,
    "type": "complaint__c",
    "description__c": "Bad product",
    "action__c": null,
    "complaint_category__c": "Wrong_Items",
    "Name": "a065i00000JkVvx"
  },
  {
    "orderId__c": "a035i00000Bwioj",
    "productTitle__c": "SAMSUNG-A2-4GB-64GB",
    "quantity__c": "1.0",
    "customerId__c": "KOL_1234",
    "date_of_complaint__c": "2023-07-18",
    "status__c": "Active",
    "Id": null,
    "type": "complaint__c",
    "description__c": "Bad product",
    "action__c": null,
    "complaint_category__c": "Wrong_Items",
    "Name": "a065i00000JjaeI"
  },
  {
    "orderId__c": "a035i00000Bwioj",
    "productTitle__c": "SAMSUNG-A2-4GB-64GB",
    "quantity__c": "1.0",
    "customerId__c": "KOL_1234",
    "date_of_complaint__c": "2023-07-18",
    "status__c": "Closed",
    "Id": null,
    "type": "complaint__c",
    "description__c": "Bad product",
    "action__c": "None",
    "complaint_category__c": "Wrong_Items",
    "Name": "a065i00000JjaeS"
  },
  {
    "orderId__c": "a035i00000Bwioj",
    "productTitle__c": "SAMSUNG-A2-4GB-64GB",
    "quantity__c": "1.0",
    "customerId__c": "KOL_1234",
    "date_of_complaint__c": "2023-07-18",
    "status__c": "Closed",
    "Id": null,
    "type": "complaint__c",
    "description__c": "Bad product",
    "action__c": "None",
    "complaint_category__c": "Wrong_Items",
    "Name": "a065i00000JjaeX"
  }
]